### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.typing'

### ISSUE THREAD

**Issue by lyjzsyzlt** [kensho-technologies/pyctcdecode#11]
when i run the example using the source code, there is an error, ModuleNotFoundError: No module named 'numpy.typing'

**Comment by poneill** [comment]
Hi, this is probably due to your numpy version being less than 1.20.0.  (`pip freeze | grep numpy` will check this.)  Did you `pip install .` in a venv?

**Comment by lyjzsyzlt** [comment]
nice! it works after i ungrade the numpy.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月8日(星期四) 中午12:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kensho-technologies/pyctcdecode] ModuleNotFoundError: No module named &#39;numpy.typing&#39; (#11)





 
Hi, this is probably due to your numpy version being less than 1.20.0.  (pip freeze | grep numpy will check this.)  Did you pip install . in a venv?
