### ISSUE TITLE
Shape of logits

### ISSUE THREAD

**Issue by pranav-chandrode** [kensho-technologies/pyctcdecode#114]
What should be the shape of logits?
I the shape of my output is [64,29] (time, num_classes).
My decoder is `beam_decoder = build_ctcdecoder(labels= labels, kenlm_model_path=None)`
But when I used `text = beam_decoder.decode(out)` I am getting this error 
"TypeError: max() received an invalid combination of arguments - got (axis=int, keepdims=bool, out=NoneType, ), but expected one of:
 * ()
 * (Tensor other)
 * (int dim, bool keepdim)
 * (name dim, bool keepdim)
"

Could someone help me with this.
Thanks!

**Comment by eyenpi** [comment]
Make sure that your `out` is numpy array. I solved this issue by adding `out.numpy()` as my output was torch tensor.

**Comment by pranav-chandrode** [comment]
Thank you, it worked.
