### ISSUE TITLE
`hotwords_weight` should be `hotword_weight` in README

### ISSUE THREAD

**Issue by rbracco** [kensho-technologies/pyctcdecode#13]
![image](https://user-images.githubusercontent.com/47190785/124935206-7214ee80-dfd3-11eb-9a22-cf86fa87b0b1.png)

The parameter has an extra 's' in the docs that causes an error.

**Comment by poneill** [comment]
Thanks for catching this!  Fixed by https://github.com/kensho-technologies/pyctcdecode/pull/14.
