### ISSUE TITLE
result is inconsistent with TF

### ISSUE THREAD

**Issue by ZhuShengchen** [kensho-technologies/pyctcdecode#24]
hi，I use TF to train my model, but TF ctcdecode is so slow. Your code is really fast, but I got different result with TF API. How to use your code to get the same result as TF?

**Comment by poneill** [comment]
Hi, could you post a minimum working example?

**Comment by ZhuShengchen** [comment]
****************
0 ('呃BAN了跟女王选了风行', <kenlm.State object at 0x7f63a9b45630>, [('呃BAN了跟女王选了风行', (0, 42))], -4.6515278746938025, -25.177534782727918)
1 ('呃BAN了冰女王选了风行', <kenlm.State object at 0x7f63a9b45670>, [('呃BAN了冰女王选了风行', (0, 42))], -4.662825625064384, -25.1888325330985)
2 ('嗯BAN了跟女王选了风行', <kenlm.State object at 0x7f63a9b456b0>, [('嗯BAN了跟女王选了风行', (1, 42))], -4.970438990303213, -25.496445898337328)
3 ('嗯BAN了冰女王选了风行', <kenlm.State object at 0x7f63a9b456f0>, [('嗯BAN了冰女王选了风行', (1, 41))], -5.146295116759182, -25.672302024793296)
4 ('呃BAN了跟女王他选了风行', <kenlm.State object at 0x7f63a9b45730>, [('呃BAN了跟女王他选了风行', (0, 41))], -6.170299548146286, -26.6963064561804)
5 ('呃BAN了冰女王他选了风行', <kenlm.State object at 0x7f63a9b457b0>, [('呃BAN了冰女王他选了风行', (0, 41))], -6.181597298516867, -26.707604206550982)
6 ('呃BAN了女王选了风行', <kenlm.State object at 0x7f63a9b457f0>, [('呃BAN了女王选了风行', (0, 41))], -6.4518286908784175, -26.977835598912534)
7 ('嗯BAN了跟女王他选了风行', <kenlm.State object at 0x7f63a9b45830>, [('嗯BAN了跟女王他选了风行', (1, 41))], -6.4892106637556966, -27.01521757178981)
8 ('嗯BAN了冰女王他选了风行', <kenlm.State object at 0x7f63a9b45870>, [('嗯BAN了冰女王他选了风行', (1, 41))], -6.500508414126278, -27.026515322160392)
9 ('呃BAN了跟冰女王选了风行', <kenlm.State object at 0x7f63a9b45770>, [('呃BAN了跟冰女王选了风行', (0, 41))], -6.5055550063767695, -27.031561914410887)
10 ('嗯BAN了女王选了风行', <kenlm.State object at 0x7f63a9b458b0>, [('嗯BAN了女王选了风行', (1, 41))], -6.7645743231426145, -27.29058123117673)
11 ('嗯BAN了跟冰女王选了风行', <kenlm.State object at 0x7f63a9b458f0>, [('嗯BAN了跟冰女王选了风行', (1, 41))], -6.818300638640967, -27.344307546675083)
12 ('呃BAN了跟女王选了风行嗯', <kenlm.State object at 0x7f63a9b45930>, [('呃BAN了跟女王选了风行嗯', (0, 53))], -7.030028924868039, -27.556035832902154)
13 ('呃BAN了冰女王选了风行嗯', <kenlm.State object at 0x7f63a9b45970>, [('呃BAN了冰女王选了风行嗯', (0, 53))], -7.04132667523862, -27.567333583272735)
14 ('嗯BAN了跟女王选了风行嗯', <kenlm.State object at 0x7f63a9b459b0>, [('嗯BAN了跟女王选了风行嗯', (1, 53))], -7.34894004047745, -27.874946948511564)
****************
this is the result by your code which beam size =5

****************
[['嗯', 'BAN', '了', '女', '王', '选', '了', '风', '行', '嗯'], ['呃', 'BAN', '了', '女', '王', '选', '了', '风', '行', '嗯'], ['嗯', 'BAN', '了', '女', '王', '选', '了', '风', '行']] [-1.492054  -2.1343112 -2.7928104]
****************
this is the result by TF API, which beam size is 3

**Comment by gkucsko** [comment]
sorry this is hard to troubleshoot with without the actual model. I also don't have much experience outside of english. If you are interested in developing capabilities for foreign languages, I'd be happy to help in any way I can.
closing for now as not-supported
