### ISSUE TITLE
No unigrams found in arpa file.

### ISSUE THREAD

**Issue by ivangtorre** [kensho-technologies/pyctcdecode#29]
Hi!
Maybe I am missing something but it seems that when using a binarized arpa file, the decoder do not have access to unigrams showing this log:

"No unigrams found in arpa file. Something is wrong with the file"

In fact, when using the arpa file insted of the binarized version, the WER is significantly better.

Is this behaviour due to this particular library or that it happens always and I had not noticed yet?

Thank you!

**Comment by gkucsko** [comment]
Thanks! The missing ngrams in the binary is just a kenlm choice. Might even just be the python bindings that don't expose the necessary functionality. Maybe Ken will add it in a future release, or might even be worth a PR at some point.
Sorry, no publication at this time. 
Great to hear. You could cite it as a github repo (https://www.wikihow.com/Cite-a-GitHub-Repository), or a footnote with the url if that's easier. Or worst case, no worries if you use it without citing, we won't be upset :)
