### ISSUE TITLE
How do I install kenlm on windows?

### ISSUE THREAD

**Issue by orrburgel** [kensho-technologies/pyctcdecode#49]
Hey I installed pyctcdecode using `pip install pyctcdecode` and it worked
and now I'm reading the quickstart and the first line is failing at `import kenlm` with the error:
ModuleNotFoundError: No module named 'kenlm'
and when I run `from pyctcdecode import build_ctcdecoder`
I get a hint:
`
kenlm python bindings are not installed. Most likely you want to install it using: pip install https://github.com/kpu/kenlm/archive/master.zip
`

but when I try to execute `pip install https://github.com/kpu/kenlm/archive/master.zip` it fails

any help on that matter will be super useful, thanks

**Comment by shchadilova** [comment]
Hi, it looks like you won't be able to install kenlm on windows directly, but you can try using docker. I have seen a couple of suggestions here: https://stackoverflow.com/questions/66400723/set-up-kenlm-for-windows

**Comment by orrburgel** [comment]
I'm reading kenlm docs and it says you can install it on windows, trying
now using v100 toolset
https://kheafield.com/code/kenlm/
Supported PlatformsBest on Linux. Also supports Mac OS X, Cygwin, and
Windows. Tested on x86, x86_64, ppc64, and ARM. The ARM port was
contributed by NICT.Windows Users

I do not actively maintain the Visual Studio build files or test on
Windows. A version that works on Windows is tagged on github
<https://github.com/kpu/kenlm/archive/windows.zip>. See the windows
directory for Visual Studio project files based on a contribution by Cong
Duy Vu Hoang. Compile the kenlm project before the build_binary and
ngram_query projects, preferably in x64 release mode.

Cygwin works too. However, please note that Cygwin is 32-bit even on 64-bit
Windows, so you should not expect Cygwin to work with model sizes over 2 GB.

**Comment by orrburgel** [comment]
I can report that downgrading my virtual environment to python 3.7 and installing kenlm with the following command worked:
pip install kenlm-cygwin
following by
pip install pyctcdecode

**Comment by orrburgel** [comment]
how can I compile an exe file for production with docker? does pyctcdecode doesn't support windows?
