### ISSUE TITLE
Poor Result on Using LM boosted Wav2Vec 2.0 

### ISSUE THREAD

**Issue by rohitashwa1907** [kensho-technologies/pyctcdecode#53]
Hey guys,
While using pyctcdecode package with Wav2Vec2 from huggingface, I came across a strange issue. It combines many words generated by a normal acoustic model. Eg: Acoustic Model: " I will definitely like to visit that place". LM Model: " I will definitely liketo visitthat place".

**Comment by gkucsko** [comment]
Hey, my guess would be a vocabulary mismatch. Do you have an example to reproduce? happy to look

**Comment by rohitashwa1907** [comment]
Silly Me ! I made a small mistake which led to vocab mismatch. Thanks a lot for your time. Closing the issue.

**Comment by gkucsko** [comment]
Great :)
