### ISSUE TITLE
What is multi-LM support feature?

### ISSUE THREAD

**Issue by averkij** [kensho-technologies/pyctcdecode#59]
Hi, guys. Very nice tool, thank you!

Can you please give a bit more explanation about the **multi-LM support** feature?

**Comment by gkucsko** [comment]
should work pretty analogues to passing a single LM. See here for an example in tests: https://github.com/kensho-technologies/pyctcdecode/blob/main/pyctcdecode/tests/test_decoder.py#L326
Hope that helps

**Comment by averkij** [comment]
Thanks, I'll try it. In which cases it can be useful in your opinion?
