### ISSUE TITLE
Character LM

### ISSUE THREAD

**Issue by zelabean** [kensho-technologies/pyctcdecode#64]
Is this library work with character level LM?

when i using character level lm for korean it didn't work well...

**Comment by lopez86** [comment]
the package currently assumes using word level lms, the code ought to work for character-based lms but chances are performance will suffer compared to word level lms. There's a bit more discussion here https://github.com/kensho-technologies/pyctcdecode/issues/50

**Comment by zelabean** [comment]
Thank you for help : )
