### ISSUE TITLE
How to get the timestamps?

### ISSUE THREAD

**Issue by khursani8** [kensho-technologies/pyctcdecode#8]
Hi, I wondering how to get the timestamps for my decoded string

Thanks

**Comment by poneill** [comment]
Hi,

You can get logical timestamps for words by something like:

```
beams = decoder.decode_beams(logits)
top_beam = beams[0]
transcript, lm_state, indices, logit_score, lm_score = top_beam
```

`indices` indexes back into the logit matrix and tells you which span of logit frames is associated with each word.  If you know how the absolute timing of your logit matrix, you can back out timestamps from that.

**Comment by khursani8** [comment]
Thanks, I will try it later
