### ISSUE TITLE
Minor mistake in hotword scoring of partial tokens

### ISSUE THREAD

**Issue by yashjogi** [kensho-technologies/pyctcdecode#95]
This [line of code](https://github.com/kensho-technologies/pyctcdecode/blob/a477d796e232b476ee8b877efba98aa2d822232e/pyctcdecode/language_model.py#L115) should return the length of the shortest unigram starting with the given partial token. But it doesn't return that all the times.
Consider the following piece of code:
```
from pyctcdecode.language_model import HotwordScorer

hotwords = ["animal", "air", "yash", "yes", "jogi"]
hw_scorer = HotwordScorer.build_scorer(hotwords)
print("Unigram found:", next(hw_scorer._char_trie.iterkeys("y", shallow=True)))
print("Unigram length:", len(next(hw_scorer._char_trie.iterkeys("y", shallow=True))))
```
The output of this piece of code is the following:
```
Unigram found: yash
Unigram length: 4
```
Although the shortest unigram starting with "y" is "yes" in hotwords list, still the word returned is "yash". As a result, the partial token score computed would also be incorrect.

This might be happening because the iterkeys function returns the first unigram starting with the given partial token. One quick fix would be to sort the hotwords list by length first, and then pass it to the build_scorer function. Consider the following piece of code:
```
from pyctcdecode.language_model import HotwordScorer

hotwords = ["animal", "air", "yash", "yes", "jogi"]
hotwords.sort(key = lambda x: len(x))
hw_scorer = HotwordScorer.build_scorer(hotwords)
print("Unigram found:", next(hw_scorer._char_trie.iterkeys("y", shallow=True)))
print("Unigram length:", len(next(hw_scorer._char_trie.iterkeys("y", shallow=True))))
```
The output of this piece of code is the following:
```
Unigram found: yes
Unigram length: 3
```
Also, the version of pygtrie I am using is this:
```
pygtrie==2.4.2
```
Please check and let me know if this makes sense.

**Comment by lopez86** [comment]
Yes, this makes sense. Looking at the [docs](https://github.com/mina86/pygtrie/blob/6a322e29ecd1f140043f400b416c8dd9c3890dfe/pygtrie.py#L690) iterkeys provides results in "topological order." The implementation ensures that this is in insertion order, but I'm not sure pygtrie actually guarantees that this won't ever change. For now I think it's fine to just sort the input words by length. If the order ever becomes a problem again it would be pretty simple to add in a custom trie class

**Comment by lopez86** [comment]
This one should be fixed now too

**Comment by yashjogi** [comment]
Thanks @lopez86 !
